version: 2.1
orbs:
    aws-s3: circleci/aws-s3@1.0.11
jobs:
    build:
        docker:
            - image: circleci/node:12.9.1-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: yarn install
            - save_cache:
                paths:
                    - node_modules
                    - ~/.npm 
                    - ~/.cache
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: yarn lint
            - run: yarn build
            - persist_to_workspace:
                root: .
                paths:
                  - .
    deploy:
        docker:
            - image: circleci/node:12.9.1-browsers
        steps:
            - attach_workspace:
                at: .
            - aws-s3/sync:
                from: build
                to: "s3://office-aid-frontend/"
                arguments: |
                  --acl public-read \
                  --cache-control "max-age=86400"
                overwrite: true
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: develop
